#ifndef DEFINES_H
#define DEFINES_H

#define TESTING 0
#define BITS 32
#define BUF_SIZE 33
#define PI 3.1415926535897932384626433832795028841971693993751058209749445923078164

enum timeIntegrator_t {
    T_FORWARD_EULER, T_BACKWARD_EULER, T_CRANK_NICOLSON
};
enum complexTimeIntegrator_t {
    CT_CRANK_NICOLSON, CT_RUNGE_KUTTA4
};
enum sIntegrator_t {
    MONTE_CARLO, GAUSS_LAGUERRE, GAUSS_HERMITE, INTERACTION_INTEGRATOR, MONTE_CARLO_IS
};
enum coordinateTypes_t {
    CARTESIAN, POLAR
};
enum differentialOpertor {
    DO_FINITE_DIFFERENCE_1d, DO_FINITE_DIFFERENCE_FIVE_POINT_1D,DO_SPECTRAL_1D
};
enum orbitalBasisType_t{
    OBT_HARMONIC_OSCILLATOR, OBT_HYDROGEN_LIKE
};
enum interactionPotential_t{
    IP_HARMONIC_OSCILLATOR, IP_SHEILDED_COULOMB
};
enum meanFieldIntegrator_t{
    MF_TRAPEZODIAL, MF_LOW_RANK_APPROXIMATION
};

#endif // DEFINES_H
